### ISSUE TITLE
Aufs patches broken for 5.4.1 kernel

### ISSUE THREAD

**Issue by bkauler** [sfjro/aufs-standalone#1]
Dr Okajima, 
EasyOS and Puppy Linux continue to use aufs, as overlayfs is just not good enough. For EasyOS, I am keen to use the 5.4 kernel because of the "lockdown" feature, however the aufs5 patches have multiple fails.

I thought that I would give overlayfs another go:
https://bkhome.org/news/201911/kernel-541-with-lockdown-and-overlayfs.html

...there are probably more issues, if I explored further. On the other hand, aufs "just works".

I want to offer my encouragement for you to acquire the new PC and be able to get back to developing aufs!

**Comment by sfjro** [comment]
bkauler:
> I want to offer my encouragement for you to acquire the new PC and be able to get back to developing aufs!

Thanks for the encouragement.
Such mail is a good motivation for me to keep developing aufs.

In October, our goverment raised the value added tax and many people
ordered something expensive like PC in the end of September.  It caused
a long waiting queue in the shop and I have to wait until middle of
December.  Sigh.

I can compile aufs on my another PC while it takes a loooong time.  I
will try the recent mainline with "lockdown" feature, and IF possible, I
will update and release a patch.
But don't expect me too much.  We have to be patiant for a looong looong
time.


J. R. Okajima

**Comment by bkauler** [comment]
Success, 5.4.1 kernel now compiles with aufs, thanks to peebee on the Puppy Forum and neko on the Porteus Forum:

https://bkhome.org/news/201912/kernel-541-with-lockdown-and-aufs.html

Works too, running it right now, in EasyOS Buster 2.1.8.
