### ISSUE TITLE
5.17.3 - failure to patch file_table.c

### ISSUE THREAD

**Issue by peabee** [sfjro/aufs-standalone#11]
patch -N -p1 < aufs5-standalone.patch
patching file fs/file_table.c
Hunk #2 FAILED at 413.
1 out of 2 hunks FAILED -- saving rejects to file fs/file_table.c.rej

diff --git a/fs/file_table.c b/fs/file_table.c
index 7d2e692b66a9..91942789c49a 100644
--- a/fs/file_table.c
+++ b/fs/file_table.c
@@ -412,6 +413,7 @@ void __fput_sync(struct file *file)
 }
 
 EXPORT_SYMBOL(fput);
+EXPORT_SYMBOL_GPL(__fput_sync);
 
 void __init files_init(void)
 {

reason? there is extra line :
EXPORT_SYMBOL(fput);
**EXPORT_SYMBOL(__fput_sync);**

void __init files_init(void)

**Comment by sfjro** [comment]
PB:
> patch -N -p1 < aufs5-standalone.patch
> patching file fs/file_table.c
> Hunk #2 FAILED at 413.
> 1 out of 2 hunks FAILED -- saving rejects to file fs/file_table.c.rej

Thanks for the report.
Confirmed that v5.17.3 has a commit
	d21287d8a458 2022-04-13 SUNRPC: Ensure we flush any closed sockets before xs_xprt_free()
which adds the line
> **EXPORT_SYMBOL(__fput_sync);**

Actually the same change was added into v5.18-rc2, and I am going to
release aufs5.x-rcN branch to support that.
I will create new aufs5.17.3 branch.  But the test may take a few days
and it may not be included in next Monday release.

Anyway please relax, sit back and wait for the new release with having a
cup of coffee or something.


J. R. Okajima

**Comment by peabee** [comment]
FYI.....
Whilst waiting (and drinking coffee) I changed aufs5-standalone.patch to simply replace EXPORT_SYMBOL(__fput_sync); with EXPORT_SYMBOL_GPL(__fput_sync);

This built successfully and "seems" to work OK.

**Comment by sfjro** [comment]
PB:
> Whilst waiting (and drinking coffee) I changed aufs5-standalone.patch to simply replace EXPORT_SYMBOL(__fput_sync); with EXPORT_SYMBOL_GPL(__fput_sync);
>
> This built successfully and "seems" to work OK.

It should be OK.
That is one solution.  Another one is to remove EXPORT_SYMBOL_GPL(...)
from aufs5-standalone.patch and leave EXPORT_SYMBOL(...) alone as it is,
which I took.
Someday I wll buy a BIALETTI espresso maker to toast.

J. R. Okajima

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs5 GIT release (v5.17.3 and v5.18-rc2)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 18 Apr 2022 00:15:03 +0900
Message-ID: ***@***.***>

o news
- - for linux-v5.17.3 and later, new branch aufs5.17.3 is released.
- - aufs: v5.18-rc2, convert kobj_type.default_attrs to default_groups

J. R. Okajima

- ----------------------------------------
- - aufs5-linux.git
  nothing new except aufs5.17.3 branch

- - aufs5-linux.git#aufs5.x-rcN
      aufs: v5.18-rc2, convert kobj_type.default_attrs to default_groups

- - aufs5-standalone.git
  ditto

- - aufs-util.git
  nothing

------- End of Blind-Carbon-Copy
