### ISSUE TITLE
Kernel 5.15.5+ Patch duplicates upstream changes fails - kernel 5.15.36

### ISSUE THREAD

**Issue by NetworkJack2** [sfjro/aufs-standalone#12]
aufs5-base.patch:
```
diff --git a/fs/sync.c b/fs/sync.c
index 1373a610dc78..b7b5a0a0df6f 100644
--- a/fs/sync.c
+++ b/fs/sync.c
@@ -28,7 +28,7 @@
  * wait == 1 case since in that case write_inode() functions do
  * sync_dirty_buffer() and thus effectively write one block at a time.
  */
-static int __sync_filesystem(struct super_block *sb, int wait)
+int __sync_filesystem(struct super_block *sb, int wait)
 {
 	if (wait)
 		sync_inodes_sb(sb);
```

The original file upstream already has removed the static, so this patch fails.

tested  with kernel 5.15.36

**Comment by sfjro** [comment]
Hello Jack,

GI Jack:
> @@ -28,7 +28,7 @@
>   * wait == 1 case since in that case write_inode() functions do
>   * sync_dirty_buffer() and thus effectively write one block at a time.
>   */
> -static int __sync_filesystem(struct super_block *sb, int wait)
> +int __sync_filesystem(struct super_block *sb, int wait)
>  {
>  	if (wait)
>  		sync_inodes_sb(sb);
> ```
>
> The original file upstream already has removed the static, so this patch fails.
>
> tested  with kernel 5.15.36

Thanks for the report.
Confirmed that v5.15.36 has
	4b7617ae04de 2022-04-27 fs: remove __sync_filesystem
which is a backport from v5.16
	9a208ba5c9af 2021-10-22 fs: remove __sync_filesystem

As you might know, aufs5.16/aufs5-base.patch already addressed it.
Now I am going to create aufs5.15.36 branch and release it on next
Monday.


J. R. Okajima

**Comment by NetworkJack2** [comment]
righteous

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs5 GIT release (v5.15.36 and v5.18-rc5)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 09 May 2022 08:47:49 +0900
Message-ID: ***@***.***>

o news
  aufs5.15.36 branch is released.
  aufs5.x-rcN is updated to follow linux-v5.18-rc5, but aufs code is unchanged

J. R. Okajima

- ----------------------------------------
- - aufs5-linux.git
  new branch aufs5.15.36

- - aufs5-standalone.git#master
  ditto

- - aufs-util.git
  nothing

------- End of Blind-Carbon-Copy

**Comment by NetworkJack2** [comment]
thanks, works now
