### ISSUE TITLE
saving rejects to file fs/file_table.c.rej

### ISSUE THREAD

**Issue by 01micko** [sfjro/aufs-standalone#14]
https://github.com/sfjro/aufs5-standalone/blob/ffd1e8d4d7a2a67ce7b39b78de0da47815d25fdc/aufs5-standalone.patch#L64

Seems linux already has this line now in 5.15.41

Thank you.

**Comment by 01micko** [comment]
My log from [kernel-kit](https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/kernel-kit) (puppylinux)

```
Adding Aufs to the kernel sources

patch -N -p1 < aufs5-kbuild.patch
patching file fs/Kconfig
patching file fs/Makefile

patch -N -p1 < aufs5-base.patch
patching file MAINTAINERS
patching file drivers/block/loop.c
patching file fs/dcache.c
patching file fs/fcntl.c
patching file fs/namespace.c
patching file fs/splice.c
patching file include/linux/fs.h
patching file include/linux/lockdep.h
patching file include/linux/mnt_namespace.h
patching file include/linux/splice.h
patching file kernel/locking/lockdep.c

patch -N -p1 < aufs5-standalone.patch
patching file fs/dcache.c
patching file fs/exec.c
patching file fs/fcntl.c
patching file fs/file_table.c
Hunk #2 FAILED at 376.
1 out of 2 hunks FAILED -- saving rejects to file fs/file_table.c.rej
patching file fs/namespace.c
patching file fs/notify/group.c
patching file fs/open.c
patching file fs/read_write.c
patching file fs/splice.c
patching file fs/xattr.c
patching file kernel/locking/lockdep.c
patching file kernel/task_work.c
patching file security/security.c
WARNING: failed to add some Aufs patches to the kernel sources.
Check it manually and either CRTL+C to bail or hit enter to go on

patch -N -p1 < aufs5-mmap.patch
patching file fs/proc/base.c
patching file fs/proc/nommu.c
patching file fs/proc/task_mmu.c
patching file fs/proc/task_nommu.c
patching file include/linux/mm.h
patching file include/linux/mm_types.h
patching file kernel/fork.c
patching file mm/Makefile
patching file mm/filemap.c
patching file mm/mmap.c
patching file mm/nommu.c
patching file mm/prfile.c
```

I checked and went on.

**Comment by sfjro** [comment]
Hello Mick,

Mick Amadio:
> https://github.com/sfjro/aufs5-standalone/blob/ffd1e8d4d7a2a67ce7b39b78de0da47815d25fdc/aufs5-standalone.patch#L64
>
> Seems linux already has this line now in 5.15.41

Thanks for the report.
Now I've confirmed that the commit in v5.18-rc2
	f00432063db1 2022-04-07 SUNRPC: Ensure we flush any closed sockets before xs_xprt_free()

was backported to v5.15.41 as
	54f6834b283d 2022-05-18 SUNRPC: Ensure we flush any closed sockets before xs_xprt_free()

I will make and release a new branch for v5.15.41.  Hopefully it will be
released on next Monday.  For now, as you already know, you can simply
remove the part

+EXPORT_SYMBOL_GPL(__fput_sync);

from the patch.


J. R. Okajima

**Comment by 01micko** [comment]
Thank you Junjiro (I hope I got that right!)

I'll close this as next Monday is good enough for me.

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs5 GIT release (v5.15.41 and v5.18)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 30 May 2022 00:50:08 +0900
Message-ID: ***@***.***>

o news
- - linux-v5.18 is released, and aufs5.18 follows it.
- - new branch aufs5.15.41 is created to follow linux-v5.15.41.

misc
- - update the donators list


J. R. Okajima

- ----------------------------------------
- - aufs5-linux.git
      aufs: update the donators list

- - aufs5-standalone.git
  ditto

- - aufs-util.git
  nothing

------- End of Blind-Carbon-Copy
