### ISSUE TITLE
kernel 5.15.41 patch fails - file_table.c

### ISSUE THREAD

**Issue by NetworkJack2** [sfjro/aufs-standalone#15]
following patch fails:

```
--- fs/file_table.c
+++ fs/file_table.c
@@ -376,6 +377,7 @@ void __fput_sync(struct file *file)
 }
 
 EXPORT_SYMBOL(fput);
+EXPORT_SYMBOL_GPL(__fput_sync);
 
 void __init files_init(void)
 {
```

*sighs*

**Comment by sfjro** [comment]
GI Jack:
> following patch fails:
>
> ```
> --- fs/file_table.c
> +++ fs/file_table.c
> @@ -376,6 +377,7 @@ void __fput_sync(struct file *file)
>  }
>  
>  EXPORT_SYMBOL(fput);
> +EXPORT_SYMBOL_GPL(__fput_sync);
>  
>  void __init files_init(void)
>  {
> ```
>
> *sighs*

Refer to https://github.com/sfjro/aufs5-standalone/issues/14 please.


J. R. Okajima

**Comment by NetworkJack2** [comment]
closing dupe. My apologies. I will be more careful next time.
