### ISSUE TITLE
aufs-5.10.117 patch fails with kernel-5.10.140

### ISSUE THREAD

**Issue by peabee** [sfjro/aufs-standalone#20]
Error msg:
patch -N -p1 < aufs5-base.patch
patching file fs/sync.c
Hunk #1 FAILED at 28.
1 out of 1 hunk FAILED -- saving rejects to file fs/sync.c.rej

Maybe caused by:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=9255a42fe7ab65bc1972ed7452966199d47b7009

**Comment by sfjro** [comment]
Hi,

PB:
> Hunk #1 FAILED at 28.
> 1 out of 1 hunk FAILED -- saving rejects to file fs/sync.c.rej
>
> Maybe caused by:
> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=9255a42fe7ab65bc1972ed7452966199d47b7009

Thanx for the report.
I'll address it as soon as possible.


J. R. Okajima

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs5 GIT release (v6.0-rc4 and v5.10.140)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 12 Sep 2022 00:22:55 +0900
Message-ID: ***@***.***>

o news
- - new branch aufs5.10.140 is released
- - aufs5.x-rcN branch simply follows the mainline v6.0-rc4
- - no new features and fixes are added


J. R. Okajima

------- End of Blind-Carbon-Copy

**Comment by peabee** [comment]
Thank you.
