### ISSUE TITLE
aufs-5.4.3 requires an amendment

### ISSUE THREAD

**Issue by peabee** [sfjro/aufs-standalone#21]
aufs-5.4.3
lines 48-67
of
https://github.com/sfjro/aufs5-standalone/blob/aufs5.4.3/aufs5-standalone.patch

can be deleted as kernel /fs/file_table.c now contains EXPORT_SYMBOL(__fput_sync);

Not sure which version of 5.4 this change occurred but 5.4.211 won't build with the above lines present. Builds and seems to work if they are deleted.

**Comment by sfjro** [comment]
PB:
> aufs-5.4.3
> lines 48-67
> of
> https://github.com/sfjro/aufs5-standalone/blob/aufs5.4.3/aufs5-standalone.patch
>
> can be deleted as kernel /fs/file_table.c now contains EXPORT_SYMBOL(__fput_sync);

Unfortunately aufs5.4 series are not supported since Sep 2021.
I won't fix.


J. R. Okajima
