### ISSUE TITLE
With new util-linux and util-linux-libs mount error

### ISSUE THREAD

**Issue by vladns** [sfjro/aufs-standalone#28]
archlinux OS, util-linux and util-linux-libs packages now introduced in archlinux, mounting disks to a shared file system does not work:
```
23:12:38 archlinux systemd[1]: Mounting /boot...
23:12:38 archlinux systemd[1]: Failed to mount /media/hdd.
23:12:38 archlinux systemd[1]: media-hdd.mount: Failed with result 'exit-code'.
23:12:38 archlinux systemd[1]: media-hdd.mount: Mount process exited, code=exited, status=32/n/a
23:12:38 archlinux mount[237]:        dmesg(1) may have more information after failed mount system call.
23:12:38 archlinux mount[237]: mount: /media/hdd: wrong fs type, bad option, bad superblock on none, missing codepage or helper program, or other error.
23:12:38 archlinux systemd[1]: Mounting /media/hdd...
23:12:38 archlinux systemd[1]: Mounted Kernel Configuration File System.
23:12:38 archlinux systemd[1]: Mounted FUSE Control File System.
23:12:38 archlinux systemd[1]: Mounting Kernel Configuration File System...
23:12:38 archlinux systemd[1]: Mounting FUSE Control File System...
23:12:38 archlinux systemd[1]: Finished Remount Root and Kernel File Systems.
```
Latest versions that this worked fine with util-linux-2.38.1-4-x86_64.pkg.tar.zst, util-linux-libs-2.38.1-4-x86_64.pkg.tar.zst
Mount line in fstab:
```
UUID=uuid /media/sdb ext4 rw,relatime,data=ordered,nofail 0 0
UUID=uuid /media/sdc ext4 rw,relatime,data=ordered,nofail 0 0
none /media/hdd aufs br:/media/sdb=rw:/media/sdc,create=mfs,sum,nofail 0 0
```

**Comment by sfjro** [comment]
Hello vladns,

> 23:12:38 archlinux systemd[1]: Failed to mount /media/hdd.
> 23:12:38 archlinux systemd[1]: media-hdd.mount: Failed with result 'exit-code'.
> 23:12:38 archlinux systemd[1]: media-hdd.mount: Mount process exited, code=exited, status=32/n/a
> 23:12:38 archlinux mount[237]:        dmesg(1) may have more information after failed mount system call.
> 23:12:38 archlinux mount[237]: mount: /media/hdd: wrong fs type, bad option, bad superblock on none, missing codepage or helper program, or other error.
> 23:12:38 archlinux systemd[1]: Mounting /media/hdd...
	:::
> UUID=uuid /media/sdb ext4 rw,relatime,data=ordered,nofail 0 0
> UUID=uuid /media/sdc ext4 rw,relatime,data=ordered,nofail 0 0
> none /media/hdd aufs br:/media/sdb=rw:/media/sdc,create=mfs,sum,nofail 0 0

I'd suggest you to check whether your kernel supports aufs or not. And
if aufs is compiled as an external module, was it loaded at the boot
time?


J. R. Okajima

**Comment by vladns** [comment]
The problem was that br:/media needs to be replaced with br=/media, i.e. the sign ":" is replaced by the sign "=" near br. There is confusion in the documentation.

**Comment by sfjro** [comment]
vladns:
> The problem was that br:/media needs to be replaced with br=/media, i.e. the sign ":" is replaced by the sign "=" near br. There is confusion in the documentation.

Thanx for the report.
The discussion was already started on aufs-users ML.
***@***.***/msg05912.html


J. R. Okajima

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Cc: ***@***.***, ***@***.***
Subject: aufs5 and aufs6 GIT release
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 24 Jul 2023 01:37:35 +0900
Message-ID: ***@***.***>

This release is not fully tested since my development environment
still suffers from SSD disaster.

o news
- - workaround for fsctx in util-linux 2.39, reported by vladns and Thomas Wei-ss-schuh.
- - new branch aufs5.10 in aufs-util.git.
- - more examples in aufs manual, suggested by ncmprhnsbl.

J. R. Okajima

- ----------------------------------------

- - aufs-linux.git for aufs[56]
      aufs: update the donators list

- - aufs-standalone.git for aufs[56]
  ditto

- - aufs-util.git#aufs5.10..aufs6.x-rcN
      new base version aufs5.10
      workaround for fsctx in util-linux 2.39
      more examples
      minor, path in an error message

------- End of Blind-Carbon-Copy
