### ISSUE TITLE
aufs-5.10 - patches missing

### ISSUE THREAD

**Issue by peabee** [sfjro/aufs-standalone#3]
There are no patches files in the https://github.com/sfjro/aufs5-standalone/tree/aufs5.10 branch.....

**Comment by sfjro** [comment]
PB:
> There are no patches files in the https://github.com/sfjro/aufs5-standalone/tree/aufs5.10 branch.....

Woops!
I'm sorry. I'll check my script to release.
Look forward to next release please.


J. R. Okajima

**Comment by TurboBlaze** [comment]
AUFS 5.10.x is the most requested.
https://i.imgur.com/OTcHDe1.jpg
Thanks for your contribution!

**Comment by sfjro** [comment]
PB:
> There are no patches files in the https://github.com/sfjro/aufs5-standalone/tree/aufs5.10 branch.....

I hope the patches in aufs5.x-rcN branch will work for you.


J. R. Okajima

**Comment by peabee** [comment]
Thanks @sfjro 
I can confirm that aufs5.x-rcN can be used to build a 5.10.4 kernel
