### ISSUE TITLE
File name is too long

### ISSUE THREAD

**Issue by vladns** [sfjro/aufs-standalone#34]
When downloading a file using qbittorrent-nox, I receive a message in the qbittorrent-nox log "File name is too long". In qbittorrent-nox (running on the same system where aufs is used), I moved the torrent from the general mount point (/media/hdd) to the mount point of one of the disks (/media/sdb) included in aufs. The download continued without error.

**Comment by sfjro** [comment]
vladns:
> When downloading a file using qbittorrent-nox, I receive a message in the qbittorrent-nox log "error: Access denied". In qbittorrent-nox (running on the same system where aufs is used), I moved the torrent from the general mount point (/media/hdd) to the mount point of one of the disks (/media/sdb) included in aufs. The download continued without error.

Is it linux-v6.6.8 + aufs6.6?
It seems aufs has to follow the changes in mainline.
But unfortunately I have no time to investigate currently.
I hope I will be back to aufs in a few months.


J. R. Okajima

**Comment by vladns** [comment]
Yes 6.6.8. I checked more thoroughly. Minus 8 characters, if you simply create a file in the root of the device “touch file_name”. It was upsetting that the ext4 file system already greatly limits the length of the name in non-Latin characters, and then they took away 8 characters.

**Comment by sfjro** [comment]
vladns:
> Yes 6.6.8. I checked more thoroughly. Minus 8 characters, if you simply c=
> reate a file in the root of the device =E2=80=9Ctouch file_name=E2=80=9D.=
>  It was upsetting that the ext4 file system already greatly limits the le=
> ngth of the name in non-Latin characters, and then they took away 8 chara=
> cters.

I don't understand what you wrote and why you changed the subject.
May I understand that your problem is not aufs'?


J. R. Okajima

**Comment by vladns** [comment]
On the shared mount point (/media/hdd), when I create a file there, I get a message that the file name is too long. When I create the same file on a disk partition (/media/sdb, which is part of the aufs shared disk), a file with the same name is created. Thus, on a shared aufs disk, the maximum length of a file name is 132 characters, versus 140 if I create it on a disk partition (/media/sdb).

**Comment by vladns** [comment]
The mount point /media/hdd is common to several disk partitions and is created when aufs runs.

**Comment by sfjro** [comment]
vladns:
> On the shared mount point (/media/hdd), when I create a file there, I get a message that the file name is too long. When I create the same file on a disk partition (/media/sdb, which is part of the aufs shared disk), a file with the same name is created. Thus, on a shared aufs disk, the maximum length of a file name is 132 characters, versus 140 if I create it on a disk partition (/media/sdb).

I don't understand well.

- what is your filesystem type, /media/hdd and /media/sdb?
- can you strace your command to create a file on them, and identify
  which systemcall returned the error?


J. R. Okajima

**Comment by vladns** [comment]
1. ext4
2. `touch Ильина_Е.А.,_Мартемьянов_М.Л._-_Строим_загородный_дом._Полное_руководство_для_современного_застройщика_Подарочные_издания._ИнтерьерИльина_Е.`
3. `touch: невозможно выполнить touch для 'Ильина_Е.А.,_Мартемьянов_М.Л._-_Строим_загородный_дом._Полное_руководство_для_современного_застройщика_Подарочные_издания._ИнтерьерИльина_Е.': Слишком длинное имя файла`

**Comment by sfjro** [comment]
vladns:
> 1. ext4
> 2. `touch Ильина_Е.А.,_Мартемьянов_М.Л._-_Строим_загородный_дом._Полное_руководство_для_современного_застройщика_Подарочные_издания._ИнтерьерИльина_Е.`
> 3. `touch: невозможно выполнить touch для 'Ильина_Е.А.,_Мартемьянов_М.Л._-_Строим_загородный_дом._Полное_руководство_для_современного_застройщика_Подарочные_издания._ИнтерьерИльина_Е.': Слишком длинное имя файла`

Unfortunately I cannot read Russian.
Try "stat -f /your/aufs/mountpoint". It will tell you the maximum name
length in aufs.


J. R. Okajima

**Comment by vladns** [comment]
In Russian (and in some other languages with hieroglyphs, in my opinion), letters are allocated not one byte, but two bytes.
```
 stat -f /media/hdd
  Файл: «/media/hdd»
    ID: 0        Длина имени: 242     Тип: aufs
Размер блока: 4096       Базисный размер блока: 4096
Блоки: Всего: 1011636    Свободно: 1011365    Доступно: 950797
Иноды: Всего: 262144     Свободно: 262114
stat -f /media/sdb
  Файл: «/media/sdb»
    ID: 1234567adf Длина имени: 255     Тип: ext2/ext3
Размер блока: 4096       Базисный размер блока: 4096
Блоки: Всего: 505818     Свободно: 505680     Доступно: 475396
Иноды: Всего: 131072     Свободно: 131054
```
stat displays length 242, versus 255. I apologize for the Russian language.

**Comment by sfjro** [comment]
vladns:
> stat displays length 242, versus 255. I apologize for the Russian language.

So aufs refuses filenames longer than 242.
Is that your case?


J. R. Okajima

**Comment by vladns** [comment]
This is not my case, I brought this up to make it clear. In my case, the number of characters is even smaller - 141, as in the example above, since a character in my language takes up 2 bytes. I understand that the difference is not significant, 241 (for Latin characters for aufs) versus 255 (for Latin characters for ext fs), but in my case there will be even fewer characters 133 (for Cyrillic characters for aufs) versus 141 (for Cyrillic characters for ext fs). It’s not good when it’s already less than others (Latin alphabet), but at the same time they even reduce what they have.

**Comment by sfjro** [comment]
vladns:
> This is not my case, I brought this up to make it clear. In my case, the =
> number of characters is even smaller - 141, as in the example above, sinc=
> e a character in my language takes up 2 bytes. I understand that the diff=
> erence is not significant, 241 (for Latin characters for aufs) versus 255=
>  (for Latin characters for ext fs), but in my case there will be even few=
> er characters 133 (for Cyrillic characters for aufs) versus 141 (for Cyri=
> llic characters for ext fs). It=E2=80=99s not good when it=E2=80=99s alre=
> ady less than others (Latin alphabet), but at the same time they even red=
> uce what they have.

I cannot get your point.
What is the exact string and its length when your get ENAMETOOLONG "File
name too long"?
Note that your locale environment may alter the lengh.


J. R. Okajima

**Comment by vladns** [comment]
I'm sorry I took up your time, forget it.
