### ISSUE TITLE
Sphinx Build Issues

### ISSUE THREAD

**Issue by NetworkJack2** [sfjro/aufs-standalone#4]
make ${MAKEFLAGS} all htmldocs

gives
Sphinx parallel build error:
docutils.utils.SystemMessage: PATHNAME/src/linux-5.10.27/Documentation/admin-guide/abi-testing.rst:19: (SEVERE/4) command 'get_abi.pl rest --enable-lineno --dir $srctree/Documentation/ABI/testing --rst-source' failed with return code 255

$ pacman -Qs sphinx
local/python-sphinx 3.5.2-1
    Python documentation generator
local/python-sphinx_rtd_theme 0.5.1-2
    Read the Docs theme for Sphinx

The build otherwise works if I do not copy documentation to the source tree

**Comment by sfjro** [comment]
Hello GI Jack,

GI Jack:
> make ${MAKEFLAGS} all htmldocs
>
> gives
> Sphinx parallel build error:
> docutils.utils.SystemMessage: PATHNAME/src/linux-5.10.27/Documentation/admin-guide/abi-testing.rst:19: (SEVERE/4) command 'get_abi.pl rest --enable-lineno --dir $srctree/Documentation/ABI/testing --rst-source' failed with return code 255

Thanks for the report.
Honestly speaking, I have never tried htmldocs.  But I could reproduce
the problem and I think this patch will fix the problem.  The error (abort
in get_abpi.pl) doesn't happen, at least.


J. R. Okajima

diff --git a/Documentation/ABI/testing/debugfs-aufs b/Documentation/ABI/testing/debugfs-aufs
index 4a6694194ba69..de739691e77ae 100644
--- a/Documentation/ABI/testing/debugfs-aufs
+++ b/Documentation/ABI/testing/debugfs-aufs
@@ -28,7 +28,7 @@ Description:
 		When the aufs mount option 'noxino' is specified, it
 		will be empty. About XINO files, see the aufs manual.
 
-What:		/debug/aufs/si_<id>/xi0, xi1 ... xiN and xiN-N
+What:		/debug/aufs/si_<id>/xi<idx>
 Date:		March 2009
 Contact:	J. R. Okajima ***@***.***>
 Description:
diff --git a/Documentation/ABI/testing/sysfs-aufs b/Documentation/ABI/testing/sysfs-aufs
index 82f9518495eae..48500c0569e65 100644
--- a/Documentation/ABI/testing/sysfs-aufs
+++ b/Documentation/ABI/testing/sysfs-aufs
@@ -6,14 +6,14 @@ Description:
 		per aufs mount, where <id> is a unique id generated
 		internally.
 
-What:		/sys/fs/aufs/si_<id>/br0, br1 ... brN
+What:		/sys/fs/aufs/si_<id>/br<idx>
 Date:		March 2009
 Contact:	J. R. Okajima ***@***.***>
 Description:
 		It shows the abolute path of a member directory (which
 		is called branch) in aufs, and its permission.
 
-What:		/sys/fs/aufs/si_<id>/brid0, brid1 ... bridN
+What:		/sys/fs/aufs/si_<id>/brid<idx>
 Date:		July 2013
 Contact:	J. R. Okajima ***@***.***>
 Description:

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs5 GIT release (v5.12-rc6)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 12 Apr 2021 00:40:19 +0900
Message-ID: ***@***.***>

o bugfix
- - doc abi, compatible to sphinx or reStructuredText, reported on github
  by GI Jack.

J. R. Okajima

- ----------------------------------------
- - aufs5-linux.git
      aufs: doc abi, compatible to sphinx or reStructuredText
      aufs: minor, comment about f_op->splice_{read,write}

- - aufs5-standalone.git
  ditto

- - aufs-util.git
      comment about NFS and udba=none

------- End of Blind-Carbon-Copy
