### ISSUE TITLE
mmap.patch fails for kernel 6.11.2

### ISSUE THREAD

**Issue by peabee** [sfjro/aufs-standalone#46]
Hunk 7 fails
Due to addition of new label - out_fput: - at line 3209 of linux-6.11.2/mm/mmap.c

If you can advise amended patch I can test it.

**Comment by sfjro** [comment]
PB:
> Hunk 7 fails
> Due to addition of new label - out_fput: - at line 3209 of linux-6.11.2/mm/mmap.c
>
> If you can advise amended patch I can test it.

Thankx for the report.
ce14f38d6ee9 2024-10-04 mm: call the security_mmap_file() LSM hook in remap_file_pages()
is the cause.
I'm going to release aufs6.11.2 on Monday. Wait for it.


J. R. Okajima

**Comment by peabee** [comment]
Also affects kernels 6.6 & 6.10 ........... and maybe others?

**Comment by sfjro** [comment]
PB:
> Also affects kernel 6.6 ........... and maybe others?

That is unexpected.
v6.11.2 contains
ce14f38d6ee9 2024-10-04 mm: call the security_mmap_file() LSM hook in remap_file_pages()
(which is originally ea7e2d5e49c0)
and it adds 'out_fput:' label as you wrote.
But v6.6 doesn't have such commit. Would you describe more details?


J. R. Okajima

**Comment by peabee** [comment]
Search for:
ea7e2d5e49c05e5db1922387b09ca74aa40f46e2
in:
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.54
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10.13
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.2

**Comment by peabee** [comment]
Thank you for the new 6.11.2 branch.

Looking at the new mmap.patch - the new label out_fput: does not occur in the aufs section of the if statement - will this cause problems? (I haven't tried to build with it yet).

**Comment by sfjro** [comment]
PB:
> Looking at the new mmap.patch - the new label out_fput: does not occur in the aufs section of the if statement - will this cause problems? (I haven't tried to build with it yet).

It should be OK.


J. R. Okajima

**Comment by peabee** [comment]
Thanks - 6.11.2 builds ok with aufs-6.11.2

6.6 and 6.10 need the same update.....

**Comment by sfjro** [comment]
PB:
> Search for:
> ea7e2d5e49c05e5db1922387b09ca74aa40f46e2
> in:
> https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.54
> https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10.13
> https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.2

I see.
I will release aufs6.6.54 and aufs6.10.13 too.


J. R. Okajima

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs6 GIT release (v6.6.54, v6.10.13, and v6.12-rc2)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 14 Oct 2024 00:44:11 +0900
Message-ID: ***@***.***>

o news
- - new aufs6.6.54 and aufs6.10.13 branches are released, requested by PB
  on github.
- - aufs source files are unchaged but supports linux-v6.12-rc2.


J. R. Okajima

------- End of Blind-Carbon-Copy

**Comment by peabee** [comment]
Thank you JR
