### ISSUE TITLE
aufs5.15 Missing Patches

### ISSUE THREAD

**Issue by bnied** [sfjro/aufs-standalone#5]
https://github.com/sfjro/aufs5-standalone/tree/aufs5.15 has no patch files.

**Comment by sfjro** [comment]
"PeeBee":
> aufs-5.15 seems to be missing the patch files...........

Ben Nied:
> https://github.com/sfjro/aufs5-standalone/tree/aufs5.15 has no patch files.

I'm sorry.  My GIT work failure.
Now I've pushed.


J. R. Okajima

**Comment by bnied** [comment]
Thank you!
