### ISSUE TITLE
aufs5.15 broken in 5.15.5

### ISSUE THREAD

**Issue by dimkr** [sfjro/aufs-standalone#6]
update_time() has been renamed to inode_update_time() (see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/inode.c?id=v5.15.5&id2=v5.15.4), breaking the patch:

```
$ cat fs/inode.c.rej
--- fs/inode.c
+++ fs/inode.c
@@ -1782,7 +1782,7 @@ EXPORT_SYMBOL(generic_update_time);
  * This does the actual work of updating an inodes time or version.  Must have
  * had called mnt_want_write() before calling this.
  */
-static int update_time(struct inode *inode, struct timespec64 *time, int flags)
+int update_time(struct inode *inode, struct timespec64 *time, int flags)
 {
        if (inode->i_op->update_time)
                return inode->i_op->update_time(ino
```

**Comment by sfjro** [comment]
Dima Krasner:
> update_time() has been renamed to inode_update_time() (see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/inode.c?id=v5.15.5&id2=v5.15.4), breaking the patch:

Thanx for the report.
I will make and release new aufs5.15.5 branch in a week or two.
If you're in a hurry and can't wwait for my release, try backporting the
commit in aufs5.x-rcN branch,
	cf1efc74d5cf4 2021-11-18 aufs: v5.16-rc1, use inode_update_time helper

J. R. Okajima

**Comment by igorpecovnik** [comment]
The same problem on 5.10.y

**Comment by sfjro** [comment]
Igor Pe ovnik:
> The same problem on 5.10.y

Ok, that is linux-v5.10.82.
Wait for aufs5.10.82 branch or apply the commit,
	cf1efc74d5cf4 2021-11-18 aufs: v5.16-rc1, use inode_update_time helper


J. R. Okajima

**Comment by bnied** [comment]
I also added the following to my build scripts to get around the patches not applying cleanly:

```
sed -i '92,104d' aufs5-base.patch
git commit -am "Fix aufs5-base.patch"
```

**Comment by bnied** [comment]
Quick and dirty workaround to get the current scripts to apply on `aufs5.10` and `aufs5.15`:

```
git cherry-pick cf1efc74d5cf4
sed -i '92,104d' aufs5-base.patch
git commit -am "Fix aufs5-base.patch"
```

The last command is something I need, due to how my packages are built, but can probably be skipped for most.
