### ISSUE TITLE
5.10 branch broken against kernel 5.10.82 and later

### ISSUE THREAD

**Issue by NetworkJack2** [sfjro/aufs-standalone#7]
They changed
inode.c here:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/inode.c?id=v5.10.82&id2=v5.10.81

so aufs5-base.patch FAILS with this:

```
--- fs/inode.c
+++ fs/inode.c
@@ -1770,7 +1770,7 @@ EXPORT_SYMBOL(generic_update_time);
  * This does the actual work of updating an inodes time or version.  Must have
  * had called mnt_want_write() before calling this.
  */
-static int update_time(struct inode *inode, struct timespec64 *time, int flags)
+int update_time(struct inode *inode, struct timespec64 *time, int flags)
 {
 	if (inode->i_op->update_time)
 		return inode->i_op->update_time(inode, time, flags);
```

New constructs in inode.c look like this:
```

/*
 * This does the actual work of updating an inodes time or version.  Must have
 * had called mnt_want_write() before calling this.
 */
int inode_update_time(struct inode *inode, struct timespec64 *time, int flags)
{
	if (inode->i_op->update_time)
		return inode->i_op->update_time(inode, time, flags);
	return generic_update_time(inode, time, flags);
}
```

Original function is not present.

**Comment by bnied** [comment]
Same problem as #6. I have a workaround [here](https://github.com/sfjro/aufs5-standalone/issues/6#issuecomment-980781751).

**Comment by sfjro** [comment]
Hello GI,

GI Jack:
> They changed
> inode.c here:
	:::
> Original function is not present.

Yes, and I'm working on it.
See also https://github.com/sfjro/aufs5-standalone/issues/6#issuecomment-980475162
and its thread.


J. R. Okajima

**Comment by NetworkJack2** [comment]
looks like 5.10.82 branch compiles.
