### ISSUE TITLE
Fail to link 5.15.x

### ISSUE THREAD

**Issue by fulalas** [sfjro/aufs-standalone#8]
Tried on 5.15.9 and 5.15.10:

```
ld: fs/inode.o: in function `__ksymtab_update_time':
inode.c:(___ksymtab_gpl+update_time+0x0): undefined reference to `update_time'
ld: fs/aufs/i_op.o: in function `aufs_update_time':
i_op.c:(.text+0x19c): undefined reference to `update_time'
make: *** [Makefile:1183: vmlinux] Error 1
```

**Comment by sfjro** [comment]
fulalas:
> Tried on 5.15.9 and 5.15.10:
>
> ```
> ld: fs/inode.o: in function `__ksymtab_update_time':
> inode.c:(___ksymtab_gpl+update_time+0x0): undefined reference to `update_time'
> ld: fs/aufs/i_op.o: in function `aufs_update_time':
> i_op.c:(.text+0x19c): undefined reference to `update_time'
> make: *** [Makefile:1183: vmlinux] Error 1
> ```

Try aufs5.15.5 branch instead of aufs5.15.


J. R. Okajima

**Comment by fulalas** [comment]
It works! Thanks! :)
